# xtreemfs docker images

xtreemfsdir:
  image: xtreemfs/xtreemfs-dir
  net: host
  volumes:
    - "./config-examples:/xtreemfs_data"
  ports:
    - "30638:30638"
    - "32638:32638"

xtreemfsmrc:
  image: xtreemfs/xtreemfs-mrc
  net: host
  volumes:
    - "./config-examples:/xtreemfs_data"
  ports:
    - "30636:30636"
    - "32636:32636"

xtreemfsosd:
  image: xtreemfs/xtreemfs-osd
  net: host
  volumes:
    - "./config-examples:/xtreemfs_data"
  ports:
    - "30640:30640"
    - "32640:32640"